### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jmount1992**
Made several changes, including:

- Moved system-configs to separate repo
- Standardised output style
- Included method to use a cached version of the tool
- Included method to test the local version of a tool
- plus other things

I have performed testing. However, I know the nuances of things. Would be good for someone else to test the new qcr script, as well as the tools themselves before merging develop with master branch.

### CODE REVIEW

**Comment by jmount1992** [comment]
@DasGuna, @Timothy-Morris, @esplinj, @andrewluiqut - are any of you able to run some tests, please?

To test, you will need to clone this repo, switch to the develop branch and invoke the tool using `./qcr`

**Comment by DasGuna** [comment]
@jmount1992 Just a few comments from my test:

- The --list option fails as an unrecognised option (note that -l works as intended). The -h and --help, as well as -c and --use-cached work as intended.
- Services function: calling update requests you to run new to create config. New fails to create new config in home directory (permission denied). Running as sudo installs at /home/root/.qcr instead of /home/$USER/.qcr. Running update afterwards then fails. 
- Services function: running current-user fails to find user (could be a result of above). No info on how to follow up error.
- Code templates: currently failing using the tool (note that this was failing outside this develop branch merge, so just a general note)

**Comment by jmount1992** [comment]
Thanks @DasGuna will look into the issues.

Are you running code_templates or code-templates? If running code-templates can you give a dump of the output please?

**Comment by DasGuna** [comment]
Running ./qcr code-templates results in:

```bash
[ERROR] No command matched 'code-templates'.

Please make a call that matches one of the following available commands:
	code_templates
	create_tag
	latex_templates
	services
	system_configs
	system_configs install
	system_configs sync
	system_configs track
	update
```

Running ./qcr code_templates results:

```bash
/dev/fd/63: line 7: syntax error near unexpected token `newline'
/dev/fd/63: line 7: `<!DOCTYPE html>'
```

**Comment by jmount1992** [comment]
@DasGuna are you on the develop branch? I ran a test and definitely is code-templates for the tool. However, I hadn't updated the code_templates to code-templates in the actual code templates repo itself. That probably doesn't make sense

**Comment by jmount1992** [comment]
Service functions issues should now have been remedied

**Pull request merged**
